#!/usr/bin/env python3
"""
Shopizy GitHub Pull Request Review Agent powered by Google AI (Gemini).
Audits PR code diffs against Clean Architecture, Project Constitution, Security, and Test Completeness.
"""

import os
import sys
import json
import urllib.request
import urllib.error

def get_env_or_exit(name: str) -> str:
    val = os.environ.get(name)
    if not val:
        print(f"::error::Missing required environment variable: {name}")
        sys.exit(1)
    return val

def github_api_request(url: str, token: str, accept: str = "application/vnd.github.v3+json", method: str = "GET", data: dict = None) -> tuple[int, str]:
    headers = {
        "Authorization": f"Bearer {token}",
        "Accept": accept,
        "User-Agent": "Shopizy-PR-Review-Agent"
    }
    payload = json.dumps(data).encode("utf-8") if data else None
    req = urllib.request.Request(url, data=payload, headers=headers, method=method)
    try:
        with urllib.request.urlopen(req) as resp:
            content = resp.read().decode("utf-8")
            return resp.status, content
    except urllib.error.HTTPError as e:
        error_content = e.read().decode("utf-8")
        print(f"::error::GitHub API call failed [{e.code}] {url}: {error_content}")
        return e.code, error_content

def call_google_ai_gemini(prompt: str, api_key: str) -> str:
    model = "gemini-2.5-flash"
    url = f"https://generativelanguage.googleapis.com/v1beta/models/{model}:generateContent?key={api_key}"
    
    payload = {
        "contents": [
            {
                "parts": [
                    {"text": prompt}
                ]
            }
        ],
        "generationConfig": {
            "temperature": 0.2,
            "maxOutputTokens": 4096
        }
    }
    
    req = urllib.request.Request(
        url,
        data=json.dumps(payload).encode("utf-8"),
        headers={"Content-Type": "application/json"},
        method="POST"
    )
    
    try:
        with urllib.request.urlopen(req) as resp:
            data = json.loads(resp.read().decode("utf-8"))
            candidates = data.get("candidates", [])
            if candidates and "content" in candidates[0]:
                parts = candidates[0]["content"].get("parts", [])
                if parts and "text" in parts[0]:
                    return parts[0]["text"]
            return "No review generated by Google AI."
    except urllib.error.HTTPError as e:
        err = e.read().decode("utf-8")
        print(f"::error::Google AI Gemini API error: {err}")
        return f"⚠️ **Google AI Review Failed**: HTTP {e.code}: {err}"

def main():
    github_token = get_env_or_exit("GITHUB_TOKEN")
    gemini_api_key = os.environ.get("GEMINI_API_KEY")
    repository = get_env_or_exit("GITHUB_REPOSITORY")
    pr_number = get_env_or_exit("PR_NUMBER")
    
    if not gemini_api_key:
        msg = (
            "### 🤖 Google AI PR Review Agent\n\n"
            "⚠️ **Gemini API Key Missing**: Please configure the `GEMINI_API_KEY` repository secret under "
            "**Settings ➔ Secrets and variables ➔ Actions ➔ New repository secret** to enable automated AI code reviews."
        )
        print("::warning::GEMINI_API_KEY secret is not set. Skipping AI review.")
        github_api_request(
            f"https://api.github.com/repos/{repository}/issues/{pr_number}/comments",
            github_token,
            method="POST",
            data={"body": msg}
        )
        return

    # 1. Fetch PR details (Title, Body)
    _, pr_json_str = github_api_request(
        f"https://api.github.com/repos/{repository}/pulls/{pr_number}",
        github_token
    )
    pr_data = json.loads(pr_json_str)
    pr_title = pr_data.get("title", "")
    pr_body = pr_data.get("body", "")

    # 2. Fetch PR Diff
    _, pr_diff = github_api_request(
        f"https://api.github.com/repos/{repository}/pulls/{pr_number}",
        github_token,
        accept="application/vnd.github.v3.diff"
    )

    # Truncate diff if extremely large to fit token limits
    max_diff_chars = 60000
    if len(pr_diff) > max_diff_chars:
        pr_diff = pr_diff[:max_diff_chars] + "\n\n... [Diff truncated for size limit] ..."

    # 3. Read Constitution if present
    constitution = ""
    constitution_path = ".specify/memory/constitution.md"
    if os.path.exists(constitution_path):
        with open(constitution_path, "r", encoding="utf-8") as f:
            constitution = f.read()

    # 4. Construct Audit Prompt
    prompt = f"""You are the Lead Systems Architect & Principal Review Agent for Shopizy, an enterprise headless e-commerce microservices platform built on .NET 10, Clean Architecture, and Spec-Driven Development (SDD).

Perform a thorough, adversarial code review of the following Pull Request:

## PR Metadata:
- **Title**: {pr_title}
- **PR Description**:
{pr_body}

## Project Constitution & Standards:
{constitution}

## Pull Request Code Diff:
```diff
{pr_diff}
```

## Review Guidelines & Pillars:
1. **Spec & Requirements Adherence**: Does the code satisfy the described requirements?
2. **Clean Architecture & Separation of Concerns**: Does code maintain strict boundaries? (Domain has zero external dependencies; Infrastructure implements interfaces; APIs use DTOs).
3. **Invariants & Domain Protections**: Are core invariants guarded? (e.g. Zero Overselling, Atomic Reservation, 15-Minute Unpaid Expiration, Price Snapshotting, Idempotency).
4. **Error Handling & RFC 7807**: Are errors handled with standard Problem Details and safe failure paths?
5. **Test Coverage & Quality**: Are unit, integration, or E2E tests meaningful with real assertions?
6. **Security & Performance**: Are there any OWASP vulnerabilities, sensitive data exposures, or performance bottlenecks?

## Expected Output Format:
Generate a clean, professional GitHub PR review markdown report structured as:
1. **Summary & Verdict**: State clearly `✅ APPROVED`, `⚠️ APPROVED WITH SUGGESTIONS`, or `❌ CHANGES REQUESTED` with a 2-3 sentence executive summary.
2. **Strengths**: Highlights of well-implemented architectural patterns or clean code.
3. **Audit Findings & Improvement Suggestions**: Specific, actionable observations with line numbers or code snippets if applicable.
4. **Verification Status**: Brief check on tests and build compliance.

Keep your response constructive, professional, and directly actionable.
"""

    print("Sending code diff to Google AI (Gemini)...")
    review_markdown = call_google_ai_gemini(prompt, gemini_api_key)

    header = "## 🤖 Google AI Code Review Agent\n\n"
    footer = "\n\n---\n*Automated review generated by Google AI Gemini in GitHub Actions.*"
    full_comment = header + review_markdown + footer

    # 5. Post review comment to GitHub PR
    print(f"Posting review comment to PR #{pr_number}...")
    status, _ = github_api_request(
        f"https://api.github.com/repos/{repository}/issues/{pr_number}/comments",
        github_token,
        method="POST",
        data={"body": full_comment}
    )

    if status in (200, 201):
        print("::notice::Google AI review comment successfully posted to Pull Request.")
    else:
        print(f"::error::Failed to post comment. Status code: {status}")

if __name__ == "__main__":
    main()
