services:
  ############################
  # Shopizy Catelog API + Dapr sidecar
  ############################
  shopizy.catelog.api:
    environment:
      - "ASPNETCORE_ENVIRONMENT=Development"
    ports:
      - "50104:50001" # Dapr instances communicate over gRPC so we need to expose the gRPC port
      - "40104:8080"

  shopizy.catelog.api-dapr:
    command: [
        "./daprd",
        "-app-id",
        "shopizypipelinecomposer",
        "-app-port",
        "8080",
        "--placement-host-address",
        "placement:50006", # Dapr's placement service can be reach via the docker DNS entry
        "--resources-path",
        "/components",
        "-config",
        "/configuration/config.yaml",
      ]
    volumes:
      - "./dapr/components/:/components"
      - "./dapr/configuration/:/configuration"

  ############################
  # Shopizy Cart API + Dapr sidecar
  ############################
  shopizy.cart.api:
    environment:
      - "ASPNETCORE_ENVIRONMENT=Development"
    ports:
      - "50200:50001" # Dapr instances communicate over gRPC so we need to expose the gRPC port
      - "41200:3500"
      - "40200:8080"

  shopizy.cart.api-dapr:
    command: [
        "./daprd",
        "-app-id",
        "shopizytransactionweb",
        "-app-port",
        "8080",
        "--placement-host-address",
        "placement:50006", # Dapr's placement service can be reach via the docker DNS entry
        "--resources-path",
        "/components",
        "-config",
        "/configuration/config.yaml",
        "--enable-api-logging",
      ]
    volumes:
      - "./dapr/components/:/components"
      - "./dapr/configuration/:/configuration"

  ############################
  # Shopizy Ordering API + Dapr sidecar
  ############################
  shopizy.ordering.api:
    environment:
      - "ASPNETCORE_ENVIRONMENT=Development"
    ports:
      - "40202:80"

  shopizy.ordering.api-dapr:
    command: [
        "./daprd",
        "-app-id",
        "shopizytransactionchangefeed",
        "-app-port",
        "8080",
        "--placement-host-address",
        "placement:50006", # Dapr's placement service can be reach via the docker DNS entry
        "--resources-path",
        "/components",
        "-config",
        "/configuration/config.yaml",
        "--enable-api-logging",
      ]
    volumes:
      - "./dapr/components/:/components"
      - "./dapr/configuration/:/configuration"