networks:
  shopizy-dapr:
    external: true
    name: shopizy-dapr

name: shopizy-engine
services:
  ############################
  # shopizy catelog api
  ############################
  shopizy.catelog.api:
    image: "akazad13/shopizycatelogapi"
    build:
      context: .
      dockerfile: src/Shopizy.Catelog.API/Dockerfile
    networks:
      - shopizy-dapr

  shopizy.catelog.api-dapr:
    image: "daprio/dapr:1.14.1-mariner"
    command: [
        "./daprd",
        "-app-id",
        "shopizycatelogapi",
        "-app-port",
        "8080",
        "--placement-host-address",
        "placement:50006", # Dapr's placement service can be reach via the docker DNS entry
        "--resources-path",
        "/components",
        "-config",
        "/configuration/config.yaml",
        "--enable-api-logging",
      ]
    volumes:
      - "./dapr/components/:/components"
      - "./dapr/configuration/:/configuration"
    depends_on:
      - shopizy.catelog.api
    # Attach the myfrontend-dapr service to the myfrontend network namespace
    network_mode: "service:shopizy.catelog.api"
    restart: on-failure

  ############################
  # shopizy cart api
  ############################
  shopizy.cart.api:
    image: akazad13/shopizycartapi
    build:
      context: .
      dockerfile: src/Shopizy.Cart.API/Dockerfile
    networks:
      - shopizy-dapr

  shopizy.cart.api-dapr:
    image: "daprio/dapr:1.14.1-mariner"
    command: [
        "./daprd",
        "-app-id",
        "shopizycatelogapi",
        "-app-port",
        "8080",
        "--placement-host-address",
        "placement:50006", # Dapr's placement service can be reach via the docker DNS entry
        "--resources-path",
        "/components",
        "-config",
        "/configuration/config.yaml",
        "--enable-api-logging",
      ]
    volumes:
      - "./dapr/components/:/components"
      - "./dapr/configuration/:/configuration"
    depends_on:
      - shopizy.cart.api
    # Attach the myfrontend-dapr service to the myfrontend network namespace
    network_mode: "service:shopizy.cart.api"
    restart: on-failure

  ############################
  # shopizy ordering api
  ############################
  shopizy.ordering.api:
    image: akazad13/shopizyorderingapi
    build:
      context: .
      dockerfile: src/Shopizy.Ordering.API/Dockerfile
    networks:
      - shopizy-dapr

  shopizy.ordering.api-dapr:
    image: "daprio/dapr:1.14.1-mariner"
    command: [
        "./daprd",
        "-app-id",
        "shopizyorderingapi",
        "-app-port",
        "8080",
        "--placement-host-address",
        "placement:50006", # Dapr's placement service can be reach via the docker DNS entry
        "--resources-path",
        "/components",
        "-config",
        "/configuration/config.yaml",
        "--enable-api-logging",
      ]
    volumes:
      - "./dapr/components/:/components"
      - "./dapr/configuration/:/configuration"
    depends_on:
      - shopizy.ordering.api
    # Attach the myfrontend-dapr service to the myfrontend network namespace
    network_mode: "service:shopizy.ordering.api"
    restart: on-failure