apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: pubsub.topic
  namespace: messaging
spec:
  type: pubsub.rabbitmq
  version: v1
  metadata:
    - name: connectionString
      value: "amqp://rabbitmq:5672"
    - name: durable
      value: false
    - name: deletedWhenUnused
      value: false
    - name: autoAck
      value: false
    - name: deliveryMode
      value: 0
    - name: requeueInFailure
      value: false
    - name: prefetchCount
      value: 0
    - name: reconnectWait
      value: 0
    - name: concurrencyMode
      value: single # single or parallel
    - name: publisherConfirm
      value: false
    - name: enableDeadLetter # Optional enable dead Letter or not
      value: true
scopes:
  - shopizycatelogapi
  - shopizycartapi
  - shopizyorderingapi
