apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: pubsub.event
spec:
  type: pubsub.kafka
  version: v1
  metadata:
    - name: brokers # Required. Kafka broker connection setting
      value: "kafka:9092"
    - name: authType # Required.
      value: "none"
scopes:
  - shopizycatelogapi
  - shopizycartapi
  - shopizyorderingapi
