apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: cachestore
  namespace: messaging
spec:
  type: state.redis
  version: v1
  metadata:
    - name: redisHost
      value: redis:6379
    - name: redisPassword
      value: ""
scopes:
  - shopizycatelogapi
  - shopizycartapi
  - shopizyorderingapi
